### ISSUE TITLE
Handle names longer then 255 chars

### ISSUE THREAD

**Issue by pixtron** [gyselroth/balloon-node-sync#10]
An api call to /node/name with a name longer then 255 characters results in `statusCode: 422` and 

```
{  
  "error":"Balloon\\Filesystem\\Exception\\InvalidArgument",
  "message":"name is longer than 255 characters",
  "code":0
}
```

**Comment by raffis** [comment]
https://github.com/gyselroth/balloon-client-desktop/issues/103

**Comment by pixtron** [comment]
Still needs to be caught
